[project]
name = "ytdl-web"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradio>=5.17.0",
    "yt-dlp[curl-cffi,default]>=2025.2.19",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
